#!/usr/bin/env bash

# FIXME: Remove this when https://github.com/ubuntu/snapcraft-desktop-helpers/pull/181 is merged

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

export QT_QPA_PLATFORMTHEME=gtk3

exec "${@}"
