name: uconfig
base: core18 
icon: desktop/uConfig.png
adopt-info: uconfig
grade: stable
summary: Datasheet pinout extractor from PDF and library Stylizer for KiCad
description: |
  Extract pinout from PDF datasheet and create KiCad schematics.
  Directly save KiCad library files. Work better with huge number of pins.

confinement: strict

apps:
  uconfig-gui:
    command: bin/uconfig_gui
    desktop: uConfig.desktop
    extensions: [kde-neon]
    plugs: &plugs [opengl, home, removable-media, network]
    environment:
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/kf5/usr/share/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

  uconfig:
    command: bin/uconfig
    extensions: [kde-neon]
    plugs: *plugs

parts:
  desktop:
    plugin: dump
    source: desktop

  kde-sdk-setup:
    plugin: nil
    build-snaps:
      - kde-frameworks-5-core18-sdk
    build-packages:
      - g++
      - mesa-common-dev
      - libglvnd-dev
      - rsync
    override-build: |
      rsync -a --ignore-existing /snap/kde-frameworks-5-core18-sdk/current/ /

  poppler:
    after: [kde-sdk-setup]
    plugin: cmake
    source: https://gitlab.freedesktop.org/poppler/poppler.git
    source-tag: poppler-0.88.0
    build-packages:
      - libfreetype6-dev
      - libfontconfig1-dev
      - libopenjp2-7-dev
    configflags:
      - -DCMAKE_BUILD_TYPE=release
    
  uconfig:
    after: [kde-sdk-setup, poppler]
    plugin: nil
    source: https://github.com/Robotips/uConfig.git
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always)"
      snapcraftctl set-version "$version"
    override-build: |
      qmake "$SNAPCRAFT_PART_SRC/src/uConfig.pro" \
        INCLUDEPATH+="$SNAPCRAFT_STAGE/include" \
        LIBS+="-L$SNAPCRAFT_STAGE/lib"
      make -j$(nproc)
      make install INSTALL_ROOT="$SNAPCRAFT_PART_INSTALL"
      cp -r "$SNAPCRAFT_PART_SRC/bin" "$SNAPCRAFT_PART_INSTALL/"

  cleanup:
    after: [uconfig]
    plugin: nil
    build-snaps: [core18, kde-frameworks-5-core18]
    override-prime: |
      # Remove all files from snap that are already included in the base snap or in
      # any connected content snaps
      set -eux
      for snap in "core18" "kde-frameworks-5-core18"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
