name: uconfig
base: core18 
icon: desktop/uConfig.png
adopt-info: uconfig
summary: Datasheet pinout extractor from PDF and library Stylizer for KiCad
description: |
  Extract pinout from PDF datasheet and create KiCad schematics.
  Directly save KiCad library files. Work better with huge number of pins.

confinement: strict

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  uconfig-gui:
    adapter: full
    command: bin/uconfig_gui
    command-chain:
      - bin/desktop-launch 
      - bin/gtk3-env-launch
    desktop: uConfig.desktop
    plugs: &plugs [opengl, x11, unity7, wayland, desktop, home, desktop-legacy, removable-media, network, gsettings]
    environment:
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      QT_QPA_PLATFORMTHEME: gtk3 # set default theme to gtk to integrate with system theme (GTK3)
      DISABLE_WAYLAND: 1
  uconfig:
    command: desktop-launch uconfig
    plugs: *plugs
parts:
  desktop:
    plugin: dump
    source: desktop
  wrapper:
    plugin: dump
    source: launchers
    organize:
      '*': bin/
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - try: [appmenu-qt5]
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
  uconfig:
    plugin: qmake
    source: https://github.com/Robotips/uConfig.git
    source-subdir: src
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
    override-build: |
      snapcraftctl build
      cp -r bin "$SNAPCRAFT_PART_INSTALL/"
    build-packages:
      - g++
      - qt5-default 
      - qttools5-dev-tools
      - libpoppler-qt5-dev
    stage-packages:
      - libqt5printsupport5
      - libqt5test5
      - libpoppler-qt5-1
      - libpoppler73
      - qtwayland5
      - qt5-gtk-platformtheme



